### ISSUE TITLE
photo gallery

### ISSUE THREAD

**Issue by fibo** [liukliuk/liukliuk.github.io#1]
See 
- [lightgallery.js](https://sachinchoolur.github.io/lightgallery.js/)
- [lightbox2-demo](http://g14n.info/lightbox2-demo/)

**Comment by liukliuk** [comment]
1. Prendiamo lightbox2 ma con le foto più grandi come compaiono in lightgallery.
2. Le scritte nella classe lb-details vanno tolte, quelle tipo

> Click the right half of the image to move forward. Image 5 of 7
1. Alleggerire il grigio del bordo. mettiamo _whitesmoke_.

**Comment by fibo** [comment]
Altra photogallery carina, con zoom: http://davidecalignano.it/project/files/medium-lightbox/demo/demo.html
