### ISSUE TITLE
menu nav

### ISSUE THREAD

**Issue by liukliuk** [liukliuk/liukliuk.github.io#3]
Mettiamo una barra di menu con le voci
- opere
- testi critici
- contatti

In opere c'è una striscia orizzontale di anteprime per ogni serie. Si può fare lo scrolling orizzontale, quando si clicca su un'immagine parte il plugin lightbox per quella serie.

Nel footer, ci sarà il link ad **All works** che sarà una pagina con tutte le opere, le anteprime le mettiamo su una layout a due colonne, che responsivo diventa di una.

**Comment by liukliuk** [comment]
esempio http://www.antoniodepascale.it/

**Comment by fibo** [comment]
**liuk**: e il menu principale era: opere - mostre - biografia/contatti
in opere 2 sezioni: Ombre (volti) - Ombre (composizioni)

**Comment by fibo** [comment]
**liuk**: anche le immagini dei volti le ho da sostituire...ti mando tutto quando sei pronto
in mostre ci sono i testi critici
e 1 foto della mostra
